name: ReflexCore CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt with click, cryptography, etc.

    - name: Install ShellCheck
      run: sudo apt-get install shellcheck

    - name: Lint Bash scripts
      run: |
        shellcheck scripts/*.sh modules/*.sh

    - name: Run Python tests
      run: |
        pytest  # Assuming you add pytest tests; if not, this can be expanded

    - name: Run full test suite
      run: |
        bash test_all.sh  # Your test_all.sh script 