name: ReflexCore CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make scripts executable
      run: |
        chmod +x test_all.sh
        chmod +x scripts/*.sh
        chmod +x modules/*.sh

    - name: Run ReflexCore Test Suite
      env:
        CI: true
      run: |
        bash test_all.sh

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck

    - name: Lint Bash scripts (warnings only)
      run: |
        echo "Running ShellCheck (warnings only, not fatal)..."
        shellcheck scripts/*.sh modules/*.sh test_all.sh || echo "ShellCheck completed with warnings (non-fatal)"

    - name: Run Python tests
      run: |
        python3 testall.py -v

    - name: Run full test suite
      env:
        CI: true
      run: |
        chmod +x test_all.sh scripts/*.sh modules/*.sh
        bash test_all.sh 